import 'react-native'
import { render, fireEvent, cleanup } from '@testing-library/react-native'
import Renderer from 'react-test-renderer'
import Home from '../screens/home'
import React from 'react'
import AsyncStorage from '@react-native-community/async-storage'